cache:
  directories:
  - $TRAVIS_BUILD_DIR/Build
  - /var/lib/docker
services:
  - docker
addons:
  apt:
    packages:
      - xvfb
install:
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
jobs:
  include:
    - stage: Build
      name: Linux
      script:
      - ./dockerbuild.sh
      - ./weld.sh node index.js cmake --alias=Linux
      - ./weld.sh node index.js build --alias=Linux
    - name: Emscripten
      script:
      - ./dockerbuild.sh
      - ./weld.sh node index.js cmake --alias=Emscripten
      - ./weld.sh node index.js build --alias=Emscripten
