cache:
  directories:
  - $TRAVIS_BUILD_DIR/Build/Cache
services:
- docker
git:
  depth: false
script:
- docker load -i ./Build/Cache/welder.tar || true
- ./dockerbuild.sh
- docker save -o ./Build/Cache/welder.tar welder
- ./weld.sh node index.js all --alias=Linux
- ./weld.sh node index.js all --alias=Emscripten
- mkdir bin
- cp Build/Linux_Emscripten_Ninja_Emscripten_Emscripten_WASM_Release/Libraries/WelderEditor/WelderEditor.* bin
- mv bin/WelderEditor.html bin/index.html
- touch bin/.nojekyll
deploy:
- provider: pages
  skip_cleanup: true
  local_dir: ./bin
  github_token: $GITHUB_TOKEN
  keep_history: false
  on:
    branch: master
- provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: Build/*/Packages/*.zip
  on:
    branch: master
