language: node_js
cache:
  directories:
  - $TRAVIS_BUILD_DIR/Build
node_js:
- '11'
addons:
  apt:
    packages:
      - xvfb
install:
- npm install
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
jobs:
  include:
    - stage: docker
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "welderengine" --password-stdin
      - npm run build
      - docker push welderengine/build
    - stage: Build
      name: Linux
      script:
      - ./weld.sh node index.js cmake --alias=Linux
      - ./weld.sh node index.js build --alias=Linux
