cache:
  directories:
  - $TRAVIS_BUILD_DIR/Build/Cache
git:
  depth: false
jobs:
  include:
  - name: Linux
    os: linux
    env:
    - CACHE_NAME=Linux
    services:
    - docker
    script:
    - ./dockerbuildserver.sh
    - ./weld.sh node index.js all --alias=Linux
  - name: Emscripten
    os: linux
    env:
    - CACHE_NAME=Emscripten
    services:
    - docker
    script:
    - ./dockerbuildserver.sh
    - ./weld.sh node index.js all --alias=Emscripten
  - name: Windows
    os: windows
    env:
    - CACHE_NAME=Windows
    language: node_js
    node_js:
    - 13
    install:
    - npm install
    - choco install doxygen.install
    - choco install llvm --version=6.0.1 --allow-downgrade
    - choco install ninja
    - df -h
    - rm -rf "C:\ProgramData\docker\windowsfilter" 2> /dev/null || true
    - rm -rf "C:\ProgramData\Package Cache" 2> /dev/null || true
    - rm -rf "C:\ProgramData\chocolatey\lib\mingw" 2> /dev/null || true
    - rm -rf "C:\Program Files (x86)\Android" 2> /dev/null || true
    - rm -rf "C:\Windows\SoftwareDistribution\Download" 2> /dev/null || true
    - rm -rf "C:\Recovery" 2> /dev/null || true
    - rm -rf "C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages" 2> /dev/null || true
    - df -h
    script:
    - node index.js all --alias=Windows
deploy:
- provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: Build/Packages/*
  on:
    tags: true
    branch: master
- provider: script
  script: ./weld.sh node index.js deploy
  on:
    tags: true
    branch: master
