cache:
  directories:
  - $TRAVIS_BUILD_DIR/Build/Cache
services:
  - docker
addons:
  apt:
    packages:
      - xvfb
install:
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
jobs:
  include:
    - stage: Build
      name: Linux
      script:
      - ALIAS=Linux ./build.sh
    - name: Emscripten
      script:
      - ALIAS=Emscripten ./build.sh
