cache:
  directories:
  - $TRAVIS_BUILD_DIR/Build/Cache
services:
  - docker
addons:
  apt:
    packages:
      - xvfb
install:
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
jobs:
  include:
    - stage: Build
      name: Linux
      script:
      - ./build.sh --parallel=1 --alias=Linux
    - name: Emscripten
      script:
      - ./build.sh --parallel=1 --alias=Emscripten
      - mkdir bin
      - cp Build/Linux_Emscripten_Ninja_Emscripten_Emscripten_WASM_Release/Libraries/WelderEditor/WelderEditor.* bin
      - mv bin/WelderEditor.html bin/index.html
      - touch bin/.nojekyll
      deploy:
        provider: pages
        local_dir: ./bin
        github_token: $GITHUB_TOKEN
        skip_cleanup: true
        keep_history: false
        on:
          branch: master
