cache:
  directories:
  - $TRAVIS_BUILD_DIR/Build/Cache
services:
  - docker
script:
- ./build.sh --parallel=1 --alias=Linux
- ./weld.sh ./Build/Linux_Linux_Ninja_Clang_SDLSTDEmpty_ANY_Release/Libraries/WelderEditor/WelderEditor -CopyPrebuiltContent -Exit
- ./build.sh --parallel=1 --alias=Emscripten
- mkdir bin
- cp Build/Linux_Emscripten_Ninja_Emscripten_Emscripten_WASM_Release/Libraries/WelderEditor/WelderEditor.* bin
- mv bin/WelderEditor.html bin/index.html
- touch bin/.nojekyll
deploy:
  provider: pages
  local_dir: ./bin
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  keep_history: false
  on:
    branch: master
