cache:
  directories:
  - $TRAVIS_BUILD_DIR/Build/Cache
services:
- docker
git:
  depth: false
jobs:
  include:
  - stage: Build
    name: Linux
    env:
    - CACHE_NAME=Linux
    script:
    - ./dockerbuildserver.sh
    - ./weld.sh node index.js all --alias=Linux
  - name: Emscripten
    env:
    - CACHE_NAME=Emscripten
    script:
    - ./dockerbuildserver.sh
    - ./weld.sh node index.js all --alias=Emscripten
deploy:
- provider: pages
  skip_cleanup: true
  local_dir: Build/Page/
  github_token: $GITHUB_TOKEN
  keep_history: false
  on:
    tags: true
    branch: master
- provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: Build/Packages/*
  on:
    tags: true
    branch: master
