cache:
  directories:
  - $TRAVIS_BUILD_DIR/Build/Cache
git:
  depth: false
jobs:
  include:
  - name: Linux
    os: linux
    env:
    - CACHE_NAME=Linux
    services:
    - docker
    script:
    - ./dockerbuildserver.sh
    - ./weld.sh node index.js all --alias=Linux
    deploy:
    - provider: releases
      skip_cleanup: true
      api_key: $GITHUB_TOKEN
      file_glob: true
      file: Build/Packages/*
      on:
        tags: true
        branch: master
  - name: Emscripten
    os: linux
    env:
    - CACHE_NAME=Emscripten
    services:
    - docker
    script:
    - ./dockerbuildserver.sh
    - ./weld.sh node index.js all --alias=Emscripten
    deploy:
    - provider: releases
      skip_cleanup: true
      api_key: $GITHUB_TOKEN
      file_glob: true
      file: Build/Packages/*
      on:
        tags: true
        branch: master
    - provider: pages
      skip_cleanup: true
      local_dir: Build/Page/
      github_token: $GITHUB_TOKEN
      keep_history: false
      on:
        tags: true
        branch: master
  - name: Windows
    os: windows
    env:
    - CACHE_NAME=Windows
    language: node_js
    node_js:
    - 13
    install:
    - df -h
    - rd /s /q "C:\ProgramData\docker"
    - df -h
    - npm install
    - choco install doxygen.install
    - choco install llvm --version=6.0.1 --allow-downgrade
    - choco install ninja
    script:
    - node index.js all --alias=Windows
    deploy:
    - provider: releases
      skip_cleanup: true
      api_key: $GITHUB_TOKEN
      file_glob: true
      file: Build/Packages/*
      on:
        tags: true
        branch: master
