cache:
  directories:
  - $TRAVIS_BUILD_DIR/Build/Cache
services:
  - docker
script:
- docker load -i ./Build/Cache/welder.tar || true
- ./dockerbuild.sh
- docker save -o ./Build/Cache/welder.tar welder
- ./weld.sh node index.js all --alias=Linux
- ./weld.sh node index.js all --alias=Emscripten
- mkdir bin
- cp Build/Linux_Emscripten_Ninja_Emscripten_Emscripten_WASM_Release/Libraries/WelderEditor/WelderEditor.* bin
- mv bin/WelderEditor.html bin/index.html
- touch bin/.nojekyll
deploy:
  provider: pages
  local_dir: ./bin
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  keep_history: false
  on:
    branch: master
