cache:
  directories:
  - $TRAVIS_BUILD_DIR/Build/Cache
services:
- docker
git:
  depth: false
jobs:
  include:
  - name: Linux
    os: linux
    env:
    - CACHE_NAME=Linux
    script:
    - ./dockerbuildserver.sh
    - ./weld.sh node index.js all --alias=Linux
    deploy:
    - provider: releases
      skip_cleanup: true
      api_key: $GITHUB_TOKEN
      file_glob: true
      file: Build/Packages/*
      on:
        tags: true
        branch: master
  - name: Emscripten
    os: linux
    env:
    - CACHE_NAME=Emscripten
    script:
    - ./dockerbuildserver.sh
    - ./weld.sh node index.js all --alias=Emscripten
    deploy:
    - provider: releases
      skip_cleanup: true
      api_key: $GITHUB_TOKEN
      file_glob: true
      file: Build/Packages/*
      on:
        tags: true
        branch: master
    - provider: pages
      skip_cleanup: true
      local_dir: Build/Page/
      github_token: $GITHUB_TOKEN
      keep_history: false
      on:
        tags: true
        branch: master
  - name: Windows
    os: windows
    env:
    - CACHE_NAME=Windows
    language: node_js
    node_js:
    - 13
    install:
    - df -h
    - npm install
    - df -h
    - choco install doxygen.install
    - df -h
    - choco install llvm --version=6.0.1
    - df -h
    - choco install ninja
    - df -h
    script:
    - df -h
    - node index.js all --alias=Windows
    - df -h
    deploy:
    - provider: releases
      skip_cleanup: true
      api_key: $GITHUB_TOKEN
      file_glob: true
      file: Build/Packages/*
      on:
        tags: true
        branch: master
